name: Sync Leetcode

on:
  workflow_dispatch: # Allows you to manually trigger it whenever you want
  schedule:
    - cron: "0 18 * * *" # Automatically triggers every single night at 12:00 AM IST (18:30 UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync history
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
